### PR TITLE
Fix formatting in insult constant

### PR DESCRIPTION
**Pull request by Razzula**
Correct me if I'm wrong, but it seems like you were missing a comma?

### CODE REVIEW

**Comment by Xomboodle** [comment]
No comma missing, they're part of the same value. It's just formatted like that as part of my IDE's integrated PEP standards (PEP 8 E501 if you're interested). Rejecting this.

**Comment by Razzula** [comment]
Thanks for clarifying! However, while PEP 8 E501 addresses line length, it doesn't mandate formatting values this way. To improve readability, especially in lists of long strings, PEP 8 recommends implicit line joining with parentheses over IDE-specific formatting. This avoids accidental concatenation and makes each item clearer, as discussed in PEP 8's [guidelines on line continuation](https://peps.python.org/pep-0008/#maximum-line-length).

> The preferred way of wrapping long lines is by using Python’s implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

Would you consider updating for consistency?

```py
INSULTS: List[str] = [
    (
        "Wow, {arg}'s face is looking real ugly today."
    ),
    (
        "Ew, do you smell that? Oh, that's just {arg}."
    ),
    (
        "We thought they went to Mordor to throw the One Ring in Mount Doom, "
        "but it was actually to get away from {arg}."
    ),
    (
        "If {arg} was a Pokémon, they would be the only one Ash wouldn't catch."
    ),
    (
        "Reverse insult! {arg} is looking lovely today, whereas you, {arg2}, "
        "wish only to spread hate across the world. Meanie."
    ),
    (
        "{arg} is proof light travels faster than sound. They appear bright until they speak."
    ),
    (
        "{arg}'s mother is a hamster and their father smells of elderberries!"
    ),
]

```

**Comment by Razzula** [comment]
I have pushed this to my branch, anyway, so feel free to reopen and use, if you want. But no worries, if not.

**Comment by Xomboodle** [comment]
Yes, happy to go with this change. You're welcome to re-open a PR, though please target the `development` branch and not `master,` as `master` is specific for releases. Since it's not an urgent fix, it'll just go into the next release :)

**Pull request closed without merging**
